import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import "./globals.css";



const robotoFont = Roboto({
  variable: "--font-roboto",
  subsets: ["latin"],
  weight: ["300","400", "500", "700"],
});



export const metadata: Metadata = {
  title: "The Tenth Floor",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
     <body className={robotoFont.className}>
   
       
        {children}
      </body>
    </html>
  );
}
